# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pidgin2adium}
  s.version = "3.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabe Berke-Williams"]
  s.date = %q{2010-08-07}
  s.description = %q{Pidgin2Adium is a fast, easy way to convert Pidgin (formerly gaim) logs to the Adium format.}
  s.email = %q{gbw@brandeis.edu}
  s.executables = ["pidgin2adium", "pidgin2adium_profiler"]
  s.extensions = ["ext/balance_tags_c/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".autotest",
     ".gitignore",
     ".rspec",
     "Gemfile",
     "History.txt",
     "LICENSE",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/pidgin2adium",
     "bin/pidgin2adium_profiler",
     "config/website.yml",
     "ext/balance_tags_c/balance_tags_c.c",
     "ext/balance_tags_c/extconf.rb",
     "lib/pidgin2adium.rb",
     "lib/pidgin2adium/balance_tags.rb",
     "lib/pidgin2adium/log_converter.rb",
     "lib/pidgin2adium/log_file.rb",
     "lib/pidgin2adium/log_parser.rb",
     "pidgin2adium.gemspec",
     "spec/pidgin2adium_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/build_profiler.rake",
     "tasks/extconf.rake",
     "tasks/extconf/balance_tags_c.rake"
  ]
  s.homepage = %q{http://github.com/gabebw/pidgin2adium}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Pidgin2Adium is a fast, easy way to convert Pidgin (formerly gaim) logs to the Adium format}
  s.test_files = [
    "spec/pidgin2adium_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 0.9.26"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<bundler>, [">= 0.9.26"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0.9.26"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

